# 202331207_Rhizieq Reflian Al Farouqh

## Import Library

In [1]:
import cv2
import numpy as np
#202331207_Rhizieq Reflian Al Farouqh

## Membaca Citra

In [2]:
citra = cv2.imread('Cat.png')
#202331207_Rhizieq Reflian Al Farouqh

In [3]:
cv2.imshow("Citra Asli", citra)
cv2.waitKey()
cv2.destroyAllWindows()
#202331207_Rhizieq Reflian Al Farouqh

## Dimensi Citra

In [4]:
print(citra.shape)
print(citra.dtype)
#202331207_Rhizieq Reflian Al Farouqh

(480, 720, 3)
uint8


## Splitting Citra

In [6]:
b = citra[:,:,0]
g = citra[:,:,1]
r = citra[:,:,2]
#202331207_Rhizieq Reflian Al Farouqh

## RGB -> Grayscale

In [7]:
panjang = len(citra)
lebar = len(citra[0])

citra_gray = np.zeros((panjang, lebar))

for i in range (panjang):
    for j in range (lebar):
        citra_gray [i,j] = 0.2989 * r[i,j] + 0.587 * g[i,j] + 0.1141 * b[i,j]

citra_gray = citra_gray.astype(np.uint8)

cv2.imshow("Citra Grayscale", citra_gray)
cv2.waitKey()
cv2.destroyAllWindows()
#202331207_Rhizieq Reflian Al Farouqh

In [8]:
print(citra)
#202331207_Rhizieq Reflian Al Farouqh

[[[201 212 209]
  [201 212 209]
  [202 212 209]
  ...
  [201 214 202]
  [203 214 202]
  [204 213 201]]

 [[201 212 209]
  [201 212 209]
  [200 213 210]
  ...
  [201 213 201]
  [202 213 201]
  [204 213 201]]

 [[201 212 209]
  [202 212 209]
  [200 214 210]
  ...
  [203 212 201]
  [203 212 201]
  [203 213 201]]

 ...

 [[ 73  42  38]
  [ 96  64  59]
  [ 96  66  57]
  ...
  [ 89  62  63]
  [ 70  38  34]
  [ 71  38  27]]

 [[ 78  47  45]
  [ 98  68  63]
  [113  83  74]
  ...
  [ 73  44  43]
  [ 73  44  36]
  [ 80  50  40]]

 [[ 89  62  61]
  [ 83  54  57]
  [ 85  54  60]
  ...
  [ 68  33  15]
  [ 80  50  34]
  [ 76  44  29]]]


In [9]:
print(citra_gray)
#202331207_Rhizieq Reflian Al Farouqh

[[209 209 209 ... 208 209 208]
 [209 209 210 ... 208 208 208]
 [209 209 211 ... 207 207 208]
 ...
 [ 44  66  66 ...  65  40  38]
 [ 49  69  83 ...  47  44  50]
 [ 64  58  59 ...  31  48  43]]


## Grayscale -> Binary

In [10]:
panjang = len(citra)
lebar = len(citra[0])

ambang = 90

citra_biner = np.zeros((panjang, lebar))

for i in range (panjang):
    for j in range (lebar):
        if citra_gray[i,j] >= ambang:
            citra_biner[i,j] = 1
        else:
            citra_biner[i,j] = 0

cv2.imshow("Citra Binary", citra_biner)
cv2.waitKey()
cv2.destroyAllWindows()
#202331207_Rhizieq Reflian Al Farouqh

In [11]:
print(citra_biner)
#202331207_Rhizieq Reflian Al Farouqh

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
